<?php

namespace Tests\Feature;

use App\Models\Quote;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Collection;
use Tests\TestCase;

class QuotesTest extends TestCase
{
    /**
     * @var Quote
     */
    private $quotes;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->quotes = new Quote();
    }

    public function testQuotesReturn()
    {
        $quotes = $this->quotes->getQuotes();

        $this->assertEquals(11, $quotes->count());
    }
}
